# Japan Birth analysis(1899-2023)

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv("../data/japan_birth_statistics_1899_2023.csv")
df = df.sort_values("year").reset_index(drop=True)  #oldest year first, newest last , rest_index fixes the index number

In [11]:
df.shape

(122, 7)

In [ ]:
df.head(10) # Top 10 values

,year,total_births,male_births,female_births,crude_birth_rate,sex_ratio_at_birth,total_fertility_rate
0,1899,1386981,713442,673539,32.0,105.9,NaN
1,1900,1420534,727916,692618,32.4,105.1,NaN
2,1901,1501591,769494,732097,33.9,105.1,NaN
3,1902,1510835,773296,737539,33.6,104.8,NaN
4,1903,1489816,763806,726010,32.7,105.2,NaN
5,1904,1440371,738230,702141,31.2,105.1,NaN
6,1905,1452770,735948,716822,31.2,102.7,NaN
7,1906,1394295,726155,668140,29.6,108.7,NaN
8,1907,1614472,818114,796358,34.0,102.7,NaN
9,1908,1662815,850209,812606,34.7,104.6,NaN

In [ ]:
df.dtypes #Checking the column name and datatypes

year                      int64
total_births              int64
male_births               int64
female_births             int64
crude_birth_rate        float64
sex_ratio_at_birth      float64
total_fertility_rate    float64
dtype: object

In [13]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
year,122.0,1.961393e+03,36.585812,1899.0,1929.250,1962.50,1992.750,2023.00
total_births,122.0,1.619319e+06,439286.360806,727288.0,1212138.000,1656495.00,1985485.500,2696638.00
male_births,122.0,8.304865e+05,224926.109670,372603.0,623344.750,849471.00,1014098.250,1380008.00
female_births,122.0,7.888323e+05,214416.989182,354685.0,588793.250,805848.00,967350.000,1316630.00
crude_birth_rate,122.0,2.082459e+01,10.534323,6.0,9.825,18.60,32.375,36.20
sex_ratio_at_birth,122.0,1.053107e+02,0.858387,102.7,104.900,105.30,105.800,108.70
total_fertility_rate,77.0,1.860779e+00,0.696069,1.2,1.390,1.72,2.050,4.54

In [16]:
df.describe(include="int64")

              year  total_births   male_births  female_births
count   122.000000  1.220000e+02  1.220000e+02   1.220000e+02
mean   1961.393443  1.619319e+06  8.304865e+05   7.888323e+05
std      36.585812  4.392864e+05  2.249261e+05   2.144170e+05
min    1899.000000  7.272880e+05  3.726030e+05   3.546850e+05
25%    1929.250000  1.212138e+06  6.233448e+05   5.887932e+05
50%    1962.500000  1.656495e+06  8.494710e+05   8.058480e+05
75%    1992.750000  1.985486e+06  1.014098e+06   9.673500e+05
max    2023.000000  2.696638e+06  1.380008e+06   1.316630e+06

# Data Cleaning

In [ ]:
# Checking the missing values from whole Table
missing_count = df.isnull().sum()
missing_count

year                     0
total_births             0
male_births              0
female_births            0
crude_birth_rate         0
sex_ratio_at_birth       0
total_fertility_rate    45
dtype: int64